package DAO.Train;

import TrainPackage.Train.Train_Pack.Train;

import java.sql.*;

public class PassengerTrain_DAO implements TrainDAO{

    public static final String URL = "jdbc:mysql://localhost:3306/p1_train";
    public static final String USER = "root";
    public static final String PASSWORD = "081101";
    private static PassengerTrain_DAO temp;

    //constructor
    private PassengerTrain_DAO() {

    }
    // singleton implementation
    public static PassengerTrain_DAO getInstance(){
        if(temp == null){
            temp = new PassengerTrain_DAO();
            return temp;
        }
        return temp;
    }


    // registering part
    @Override
    public String registerTrain(String train_name,String starting_point,String destination){

        ensureTrainTable();
        String insertQuery = "INSERT into Passenger_Train (Train_Name,Starting_Point,Destination) VALUES (?,?,?)";
        try(Connection connection = DriverManager.getConnection(URL,USER,PASSWORD);
            PreparedStatement pstmt = connection.prepareStatement(insertQuery,Statement.RETURN_GENERATED_KEYS) ){

            pstmt.setString(1,train_name);
            pstmt.setString(2,starting_point);
            pstmt.setString(3,destination);

            int rowsUpdated = pstmt.executeUpdate();
            System.out.println("rowsUpdated = "+ rowsUpdated);
            if(rowsUpdated > 0){
                // the below part wasnt working as expected it was getting false here -- if(resultSet.next()) -- because mysql doest consider keys generated by triggers as auto generated keys.
                //try(ResultSet resultSet = pstmt.getGeneratedKeys()){
                //                    if(resultSet.next()){
                //                        String train_id = resultSet.getString(1);
                //                        System.out.println("Train registration successful with id: "+train_id+". Name : "+train_name);
                //                        return train_id;
                //                    }
                //                }
                //            }
                String selectQuery = "SELECT TrainID FROM Passenger_Train WHERE Train_Name = ?";
                try (PreparedStatement selectStmt = connection.prepareStatement(selectQuery)) {
                    selectStmt.setString(1, train_name);
                    try (ResultSet resultSet = selectStmt.executeQuery()) {
                        if (resultSet.next()) {
                            String train_id = resultSet.getString("TrainID");
                            System.out.println("Train registration successful with ID: " + train_id + ". Name: " + train_name);
                            return train_id;
                        }
                    }
                }catch (SQLException e) {
                    System.out.println("Error getting generated keys: " + e.getMessage());
                }

            }else{
                System.out.println("something wrong train id not retreived");
            }
        }catch (SQLException e){
            System.out.println("Error in connecting to database :"+ e.getMessage());
            System.out.println("Sql state :"+e.getSQLState());
            System.out.println("error code "+e.getErrorCode());
        }
        System.out.println("going to return null");
        return null ;
    }

    public static void ensureTrainTable(){
        System.out.println("ensuring train table is there or not");
        String createTableQuery = "CREATE TABLE IF NOT EXISTS Passenger_Train ("
                + "TrainID VARCHAR(20) PRIMARY KEY, "
                + "Train_Name VARCHAR(50) NOT NULL UNIQUE, "
                + "Starting_Point VARCHAR(50) NOT NULL, "
                + "Destination VARCHAR(50) NOT NULL)";

        try (Connection connection = DriverManager.getConnection(URL, USER, PASSWORD);
             Statement stmt = connection.createStatement()) {

            stmt.executeUpdate(createTableQuery);
            System.out.println("Checked: Passenger_Train table exists or created.");

        } catch (SQLException e) {
            System.out.println("Error ensuring Passenger_Train table: " + e.getMessage());
        }
    }

}

//   Trigger used to generate train id
//            DROP TRIGGER IF EXISTS generate_trainID;
//            DELIMITER //
//
//            CREATE TRIGGER generate_trainID
//            BEFORE INSERT ON passenger_train
//            FOR EACH ROW
//                    BEGIN
//            DECLARE random_num INT;
//            SET random_num = FLOOR(10000 + (RAND() * 90000));
//            SET NEW.TrainID = CONCAT(LEFT(NEW.Train_Name, 3), random_num);
//            END;
//            //
//
//            DELIMITER ;